# Generated by Django 4.1.3 on 2022-11-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_creators_alter_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brands',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ('title',), 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='creators',
            options={'ordering': ('title',), 'verbose_name_plural': 'Creators'},
        ),
    ]
