# Generated by Django 4.1.3 on 2022-11-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_category_brands_alter_brands_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='creators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.creators'),
            preserve_default=False,
        ),
    ]
