# Generated by Django 4.1.3 on 2022-11-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_brands_post_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creators',
        ),
        migrations.DeleteModel(
            name='Creators',
        ),
    ]
