databases:
  - name: aftershave_u
    databaseName: aftershave_u
    user: aftershave_u

services:
  - type: web
    name: aftershave_u
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aftershave_u
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4